<?php

/**
 * Implements hook_theme_suggestions_page_alter()
 */
function emoney_main_theme_suggestions_page_alter(array &$suggestions, array $variables) {
    $route_name = \Drupal::routeMatch()->getRouteName();
    $route_parts = explode('.', $route_name);

    if (count($route_parts) == 2 && $route_parts[0] === 'system') {
        $code = $route_parts[1];
        if (is_numeric($code)) {
            $suggestions[] = 'page__' . $code;
        }
    }
}

?>