<?php

/**
 * Implements hook_theme_suggestions_page_alter()
 */
function emoney_main_theme_suggestions_page_alter(array &$suggestions, array $variables) {
    $route_name = \Drupal::routeMatch()->getRouteName();
    $route_parts = explode('.', $route_name);

    if (count($route_parts) == 2 && $route_parts[0] === 'system') {
        $code = $route_parts[1];
        if (is_numeric($code)) {
            $suggestions[] = 'page__' . $code;
        }
    }
}

/**
 * Implements hook_theme_suggestions_page_alter()
 */
function emoney_main_theme_suggestions_node_alter(array &$suggestions, array $variables) {
    $path = \Drupal::service('path.current')->getPath();
    $alias = \Drupal::service('path.alias_manager')->getAliasByPath($path);

    if ($alias == '/apis' || $alias == '/collections') {
        $suggestions[] = 'node__apis';
    }
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function emoney_main_menu_links_discovered_alter(&$links) {
  $links['user.logout']['class'] = 'Drupal\emoney_main\Plugin\Menu\EmoneyLoginLogoutMenuLink';
}

